import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Music Academy - VT",
  description: "Created by Vinay-T with the help of 'Chai-aur-Code' || Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className={inter.className}>
        <Toaster />
        
        <header className="relative w-full flex items-center justify-center ">
          <Navbar />
        </header>
        
        <main>
          {children}
        </main>

        </body>
    </html>
  );
}
